#!/usr/bin/env ruby

$: << "lib"
require 'dns-checker'

zone = ARGV.first
zone = zone + "." unless zone.end_with? "."

cache = DNSChecker::ResolvCache.new(
  DNSChecker::ResolvCacheFetcher.new,
  DNSChecker::ResolvCacheStore.new("var/cache")
)

# servers = DNSChecker::RootServers::SERVER_IPV4
# DNSChecker::ZoneWalker.new(cache, servers).walk(zone)

full_resolver = DNSChecker::FullResolver::Resolver.new(
  DNSChecker::FullResolver::ZoneCache.new,
  DNSChecker::FullResolver::HostCache.new,
  cache
)

ans = full_resolver.find_answer(Resolv::DNS::Name.create(zone), Resolv::DNS::Resource::IN::A)
puts ""
puts ""
p ans
puts ""

STDOUT.reopen(File.open('zone.dot', 'w'))
DNSChecker::GraphMaker.new(full_resolver.zone_cache, full_resolver.host_cache).render_dot()
